import monkey1 from '../../images/SuperHotDrop/1.jpg'
import monkey2 from '../../images/SuperHotDrop/2.jpg'
import monkey3 from '../../images/SuperHotDrop/3.jpg'
import monkey4 from '../../images/SuperHotDrop/4.jpg'
import monkey5 from '../../images/SuperHotDrop/5.jpg'
import monkey6 from '../../images/SuperHotDrop/6.jpg'
import monkey7 from '../../images/SuperHotDrop/7.jpg'
import monkey8 from '../../images/SuperHotDrop/8.jpg'

const SuperHotDrops = [
    {
        image: monkey1,
        title: 'Monkey',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Monkey',
    },
    {
        image: monkey2,
        title: 'Monkey',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Monkey',
    },
    {
        image: monkey3,
        title: 'Monkey',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Monkey',
    },
    {
        image: monkey4,
        title: 'Monkey',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Monkey',
    },
    {
        image: monkey5,
        title: 'Monkey',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Monkey',
    },
    {
        image: monkey6,
        title: 'Monkey',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Monkey',
    },
    {
        image: monkey7,
        title: 'Monkey',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Monkey',
    },
    {
        image: monkey8,
        title: 'Monkey',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Monkey',
    },
    {
        image: monkey8,
        title: 'Cars',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Cars',
    },
    {
        image: monkey8,
        title: 'Cars',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Cars',
    },
    {
        image: monkey8,
        title: 'Cars',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Cars',
    },
    {
        image: monkey8,
        title: 'Cars',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Cars',
    },
    {
        image: monkey8,
        title: 'Cars',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Cars',
    },
    {
        image: monkey8,
        title: 'Cars',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Cars',
    },
    {
        image: monkey2,
        title: 'Other',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Other',
    },
    {
        image: monkey2,
        title: 'Other',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Other',
    },
    {
        image: monkey2,
        title: 'Other',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Other',
    },
    {
        image: monkey2,
        title: 'Other',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Other',
    },
    {
        image: monkey2,
        title: 'Other',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Other',
    },
    {
        image: monkey2,
        title: 'Other',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Other',
    },
    {
        image: monkey2,
        title: 'Other',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Other',
    },
    {
        image: monkey2,
        title: 'Other',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Other',
    },
    {
        image: monkey4,
        title: 'Other 2',
        price: '0.25 ETH',
        order: '1 of 32',
        initialTime: '3h 25m 3s',
        category: 'Other 2',
    },
]

export default SuperHotDrops
